const products = [
  {
      _id: '1',
      name: 'Apple AirPods',
      image: '/images/airpods.jpg',
      description: 'Wireless Bluetooth earbuds with high-quality sound and noise cancellation.',
      brand: 'Apple',
      category: 'Audio',
      price: 199.99,
      countInStock: 12,
      rating: 4.7,
      numReviews: 150,
  },
  {
      _id: '2',
      name: 'Amazon Alexa',
      image: '/images/alexa.jpg',
      description: 'Smart speaker with voice control, music streaming, and smart home integration.',
      brand: 'Amazon',
      category: 'Smart Home',
      price: 99.99,
      countInStock: 20,
      rating: 4.5,
      numReviews: 95,
  },
  {
      _id: '3',
      name: 'Canon Camera',
      image: '/images/camera.jpg',
      description: 'Professional-grade DSLR camera with 20MP resolution and 4K video recording.',
      brand: 'Canon',
      category: 'Photography',
      price: 499.99,
      countInStock: 5,
      rating: 4.8,
      numReviews: 75,
  },
  {
      _id: '4',
      name: 'Logitech MX Master 3 Mouse',
      image: '/images/mouse.jpg',
      description: 'Advanced wireless mouse with customizable buttons and ultra-fast scrolling.',
      brand: 'Logitech',
      category: 'Accessories',
      price: 89.99,
      countInStock: 10,
      rating: 4.7,
      numReviews: 85,
  },
  {
      _id: '5',
      name: 'iPhone 12',
      image: '/images/phone.jpg',
      description: 'The iPhone 12 features a 6.1-inch Super Retina XDR display and A14 Bionic chip.',
      brand: 'Apple',
      category: 'Electronics',
      price: 799.99,
      countInStock: 8,
      rating: 4.6,
      numReviews: 120,
  },
  {
      _id: '6',
      name: 'Sony PlayStation 5',
      image: '/images/playstation.jpg',
      description: 'Next-gen gaming console with ultra-fast SSD and immersive gameplay experience.',
      brand: 'Sony',
      category: 'Gaming',
      price: 499.99,
      countInStock: 6,
      rating: 4.9,
      numReviews: 200,
  }
];

export default products;
